version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./frontend/src:/home/node/app/frontend/src
    container_name: frontend
    expose:
      - '5173'
      - '24678'
    ports:
      - '5173:5173'
      - '24678:24678' # Vite dev server websocket for hot reload
    command: yarn dev

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./backend/src:/home/node/app/backend/src
    container_name: backend
    expose:
      - '3000'
    ports:
      - '3000:3000'
    environment:
      # This ENV is used by backend and migrations
      DATABASE_URL: postgres://postgres:brainiac@db:5432/postgres
    command: yarn dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: brainiac
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: brainiac
    ports:
      - '5050:80'